# GitHub Action, die aus den LiaScript-Materialien des Wintersemester 2021/22 ein
# Skript generiert

name: GeneratePdf

on:
  push:
    branches:
      - master

jobs:
  convert_via_pdf:
    runs-on: ubuntu-18.04
    container:
      image: docker://mirisbowring/texlive_ctan_full:2019
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          ref: master
        # Ausf√ºhren des Parsers, der bestimmte Elemente im LiaCode entfernt
      - name: Run preprocessing
        run : |
          mkdir output
          python3 .github/workflows/preprocessing.py
        # Installation der notwendigen Pandoc tools
      - name: Install pandoc
        run: |
          sudo apt install pandoc
        # Generierungsprozess
      - name: Run pandoc markdown to pdf
        run: |
          pandoc --toc -N --top-level-division=chapter -H .github/workflows/head.tex -V linkcolor:blue --pdf-engine=xelatex --listings --include-in-header=.github/workflows/listings.tex -o output/script.pdf *.mdx
        # Speichern als Artifact
      - uses: actions/upload-artifact@master
        with:
          name: pdf
          path: output
